-- Script generated by Redgate Compare v1.23.0.23871


-- deployment: Dropping orders.LastModBy...
ALTER TABLE orders DROP COLUMN LastModBy;


-- deployment: Creating contact.Old_Col...
ALTER TABLE contact ADD COLUMN Old_Col int(11) NULL;


-- deployment: Altering contact.id...
ALTER TABLE contact MODIFY COLUMN id int(11) NULL;

