-- Script generated by Redgate Compare v1.22.1.23470


-- deployment: Creating active_employees...
CREATE VIEW active_employees AS select `employees`.`EmployeeID` AS `EmployeeID`,`employees`.`FirstName` AS `FirstName`,`employees`.`LastName` AS `LastName`,`employees`.`Position` AS `Position` from `employees`;

