-- Script generated by Redgate Compare v1.23.0.23871


-- deployment: Dropping GetCustomerOrders...
DROP PROCEDURE GetCustomerOrders;


-- deployment: Creating employees.LastModBy...
ALTER TABLE employees ADD COLUMN LastModBy date NULL;
update employees set LastModBy = "2024-01-01"

