-- Script generated by Redgate Compare v1.23.0.23871


-- deployment: Creating orders.LastModBy...
ALTER TABLE orders ADD COLUMN LastModBy int(11) NULL;


-- deployment: Dropping contact.Old_Col...
ALTER TABLE contact DROP COLUMN Old_Col;


-- deployment: Altering contact.id...
ALTER TABLE contact MODIFY COLUMN id int(20) NULL;

