-- Script generated by Redgate Compare v1.22.1.23470


-- deployment: Dropping productsales...
DROP VIEW productsales;


-- deployment: Dropping customerordersummary...
DROP VIEW customerordersummary;


-- deployment: Dropping orders.orders_ibfk_1...
ALTER TABLE orders DROP FOREIGN KEY orders_ibfk_1;


-- deployment: Dropping orderdetails.orderdetails_ibfk_2...
ALTER TABLE orderdetails DROP FOREIGN KEY orderdetails_ibfk_2;


-- deployment: Dropping products...
DROP TABLE products;


-- deployment: Dropping orderdetails.orderdetails_ibfk_1...
ALTER TABLE orderdetails DROP FOREIGN KEY orderdetails_ibfk_1;


-- deployment: Dropping employees...
DROP TABLE employees;


-- deployment: Dropping customers...
DROP TABLE customers;


-- deployment: Dropping GetCustomerOrders...
DROP PROCEDURE GetCustomerOrders;


-- deployment: Dropping AddEmployee...
DROP PROCEDURE AddEmployee;


-- deployment: Dropping CalculateTotalOrderAmount...
DROP FUNCTION CalculateTotalOrderAmount;


-- deployment: Dropping orders.CustomerID...
DROP INDEX CustomerID ON orders;


-- deployment: Dropping orders...
DROP TABLE orders;


-- deployment: Dropping orderdetails.ProductID...
DROP INDEX ProductID ON orderdetails;


-- deployment: Dropping orderdetails.OrderID...
DROP INDEX OrderID ON orderdetails;


-- deployment: Dropping orderdetails...
DROP TABLE orderdetails;

